version: '3.1'

services:
  api:
    build: .
    environment:
      DB_DRIVER: "postgres"
      DB_URI: "host=db user=postgres dbname=shortener password=suppersecret sslmode=disable"
      DB_MAX_OPEN: 10
      DB_MAX_IDLE: 20
      INMEM_CACHE_LEN: 10000
      HASH_SALT: mysuppersalt
      HASH_MIN_LEN: 4
      SERVICE_DOMAIN: short
      HTTP_PORT: ":3001"
      REDIS_ADDRESS: "redis:6379"
      REDIS_MAX_IDLE: 100
      REDIS_IDLE_TIME: 100
    depends_on:
      - db
    restart: always
    ports:
      - 3001:3001
  
  redis:
    image: redis
    ports:
      - 6380:6379

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=suppersecret
      - POSTGRES_DB=shortener
    ports:
      - 5432:5432
