// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/rs/zerolog"
	"urlshortener/internal/hashids"
	"urlshortener/internal/inmem"
	"urlshortener/internal/postgres"
	"urlshortener/internal/service"
	"urlshortener/internal/transport/http"
)

import (
	_ "github.com/joho/godotenv/autoload"
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func provideApp(logger zerolog.Logger, c *Config) *App {
	store := providePostgres(c)
	config := provideAPIConfig(c)
	serviceConfig := provideServiceConfig(c)
	cache := provideCache(c)
	decoder := provideHashDecoder(c)
	serviceService := &service.Service{
		Config: serviceConfig,
		Store:  store,
		Cache:  cache,
		Codec:  decoder,
	}
	api := &http.Api{
		Config: config,
		Svc:    serviceService,
	}
	app := &App{
		Store: store,
		API:   api,
		Log:   logger,
	}
	return app
}

// wire.go:

func providePostgres(c *Config) *postgres.Store {
	return &postgres.Store{
		Config: c.PG,
	}
}

func provideAPIConfig(c *Config) *http.Config {
	return c.HTTP
}

func provideServiceConfig(c *Config) service.Config {
	return *c.Service
}

func provideHashDecoder(c *Config) hashids.Decoder {
	return hashids.New(*c.HashCodec)
}

func provideCache(c *Config) *inmem.Cache {
	return inmem.New(*c.Inmem)
}
